### ISSUE TITLE
Removing from whitelist deletes whole whitelist.csv

### ISSUE THREAD

**Issue by 0x0465** [olafhartong/ThreatHunting#93] opened 2022-05-23 17:37 UTC
Adding to the whitelist works just flawless, but when I try to remove any record it deletes everything from that particular csv I'm using.
![gif](https://user-images.githubusercontent.com/35386414/169875982-312c6f78-b427-4908-84c7-d0a087f00e84.gif)
Here I filled it with bogus data, but it does the same thing with real ones too, with or withour using wildcards.
version 1.5.0

**Comment by dr6g1** [comment] 2022-05-24 19:25
I found the cause, pull request sent
https://github.com/olafhartong/ThreatHunting/pull/94

**Comment by olafhartong** [comment] 2022-08-31 07:02
Thanks for this! Closing with your fix

**Closed by olafhartong** 2022-08-31 07:02 UTC

**Comment by dstaulcu** [comment] 2022-08-31 20:49
Thanks for closing so many PRs today.  Did Florian's Twitter post about his GitHub bullying tactic get under your skin?  Jokes aside, Looking forward to keeping you busy with this project as I progress from process create tuning phase to focus on other event types.
